# Generated by Django 4.1.4 on 2023-01-25 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplecorrectquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='numericalquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='question_ptr',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_quiz',
            new_name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_created',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='inv.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='inv.question'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='quiz_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='inv.quizresult'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz_taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
        migrations.DeleteModel(
            name='MultipleCorrectQuestion',
        ),
        migrations.DeleteModel(
            name='NumericalQuestion',
        ),
        migrations.DeleteModel(
            name='QuizTaker',
        ),
        migrations.DeleteModel(
            name='TrueFalseQuestion',
        ),
    ]
