# Generated by Django 4.1.4 on 2023-01-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_choice_useranswer_rename_n_score_question_pen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.TextField(max_length=65535),
        ),
    ]
