# Generated by Django 4.1.4 on 2023-01-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_alter_question_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.CharField(default='Enter your Question Here', max_length=255),
        ),
    ]
